name: Modelops deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [ml_ci_cd]

jobs:
  ml_ci_cd:
    runs-on: ubuntu-latest
    steps:
      # 1. Clonar el repositorio
      - uses: actions/checkout@v4

      # 2. Configurar Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      # 3. Mostrar versión de Python y pip
      - name: Show Python & pip
        run: |
          python --version
          python -m pip --version

      # 4. Actualizar pip, setuptools y wheel para evitar conflictos
      - name: Upgrade pip/setuptools/wheel
        run: |
          python -m pip install --upgrade "pip<25" "setuptools<70" "wheel"

      # 5. Cachear dependencias pip para acelerar builds
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py38-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-py38-pip-

      # 6. Instalar dependencias del proyecto
      - name: Install requirements
        env:
          PIP_ONLY_BINARY: ":all:"
        run: python -m pip install -r requirements.txt

      # 7. Entrenar el modelo de Machine Learning
      - name: Train model
        run: python model/train.py
