name: Modelops deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [ml_ci_cd]

jobs:
  ml_ci_cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Show Python & pip
        run: |
          python --version
          python -m pip --version

      - name: Upgrade pip/setuptools/wheel (safe for 3.8)
        run: |
          python -m pip install --upgrade "pip<25" "setuptools<70" "wheel"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py38-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-py38-pip-

      - name: train model
        run: python model/train.py


      - name: Install requirements
        env:
          PIP_ONLY_BINARY: ":all:"   # evita compilar desde fuente
        run: python -m pip install -r requirements.txt
